### ISSUE TITLE
Enhancement: Improve Font and Back-End

### ISSUE THREAD

**Issue by JerJohn15** [JerJohn15/viasat-hackathon#1]
The following enhancements should be made:

**Front-End**:
- [ ] The side menu should have the ability to expand and collapse 
- [ ] When clicking on a targeted location, the user should be shown a popup with a short description of the information contained in the side menu about that person.
- [ ] The form showing each person's data should be formatted better

**Backend:**
- [ ] The database needs to be checked for invalid values (some errors are shown )
